### ISSUE TITLE
Pokemon name and images not lining up for species after Inteleon

### ISSUE THREAD

**Issue by VioletT1ger** [spinfal/pokemon-smash-or-pass#6]
Images seem to follow national dex order according to bulbapedia, but some of the names for the family lines are in a different order causing some to not line up
![image](https://user-images.githubusercontent.com/16064843/154121786-0edfdb7c-462a-4a88-bf36-141d7a7dc729.png)

**Comment by spinfal** [comment]
I see, I'll look into this and fix the Pokemon name list when I'm back home!
